### ISSUE TITLE
Making the font Google Fonts Compatible

### ISSUE THREAD

**Issue by ArpanSriv** [marcologous/hanken-grotesk#3]
Hi @marcologous we can track the changes required in the font for GoogleFonts here!

The following things are required as per the [Mastering New Fonts Guidelines](https://github.com/googlefonts/gf-docs/tree/master/MasteringNewFamiliesForGF):

- [ ] Repo Layout
- [ ] Design Inspection
- [ ] Update Metadata so it's correct
- [ ] Generate TTFs and check with Fontbakery

I believe the first 3 steps are done right?
Let me know if I could be of any help.

**Comment by marcologous** [comment]
Thanks @ArpanSriv ! This has been resolved already
