### ISSUE TITLE
The figures (0-9 and currencies) should have the same width across all 18 weights

### ISSUE THREAD

**Issue by cssobral2013** [marcologous/hanken-grotesk#30]
Maybe... 1200.

**Comment by marcologous** [comment]
Hi, @cssobral2013 they currently have the same width. Are you referencing the current dev files?

**Comment by cssobral2013** [comment]
@marcologous:
(1) The dev files (glyphs files) also display this issue, as shown on screenshots below. I used FontLab 7 because it's the ONLY font editor that can view glyphs files in non-Mac OS'es.
![Capturar](https://user-images.githubusercontent.com/19995437/85226843-f76d3700-b3af-11ea-8f5b-71511b7975f8.PNG)
![Capturar-thin](https://user-images.githubusercontent.com/19995437/85226846-f805cd80-b3af-11ea-99b9-11370a8a9202.PNG)


(2) More specifically, the advance width of 0-9 and currencies should remain equal across all 9 weights and their italics. This is desired, for example, on typesetting tables.

**Comment by marcologous** [comment]
@cssobral2013 the default numerals are monospaced which is common to a lot of workhorse type fonts. The proportional width ones are the glyphs with the .lf (lining figures) in the name.

**Comment by cssobral2013** [comment]
@marcologous - More specifically, the issue should mean the following:
Try to type, without quotes,
"$€£01234567.,89"
in Regular in a row, then type the same in any other weight. The characters should perfectly align vertically.

**Comment by marcologous** [comment]
@cssobral2013 True! Definitely need to fix it.

**Comment by cssobral2013** [comment]
@marcologous - Waiting for it, thank you!

Em seg, 6 de jul de 2020 4:32 PM, Alfredo Marco Pradil <
notifications@github.com> escreveu:

**Comment by felipesanches** [comment]
I think this is related to the discussion at https://github.com/googlefonts/fontbakery/issues/2278

**Comment by felipesanches** [comment]
also take a look at this tutorial:
https://glyphsapp.com/tutorials/figure-sets

**Comment by marcologous** [comment]
@cssobral2013 True! This is hard to achieve when there is a huge difference between the two master weights = Thin to Ultra/Black/Heavy. But It should be easy in our case. @felipesanches yes that is exactly the same issue.
