### ISSUE TITLE
Fontmake WARNING: glyphsLib.builder.axes:Instance user-space location (100) redefined by ...

### ISSUE THREAD

**Issue by felipesanches** [marcologous/hanken-grotesk#55]
The font files seem to be built correctly but we still get this suspicious warning on fontmake:
 
![Screenshot from 2020-08-01 11-49-55](https://user-images.githubusercontent.com/213676/89104134-5a111400-d3ed-11ea-8153-4b98dd131417.png)

(https://github.com/google/fonts/issues/1412#issuecomment-667543651)

**Comment by marcologous** [comment]
Hey @felipesanches have you figured out the issue with this one?

**Comment by vv-monsalve** [comment]
Not receiving this warning on the latest test performed. Closing this here

**Comment by felipesanches** [comment]
thanks, @vv-monsalve
