### ISSUE TITLE
Mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [marcologous/hanken-grotesk#56]
The horizontal bar of + − ÷ should be the same (same length, same thickness), and aligned vertically (in the middle) with × =.

<img width="1700" alt="Hanken Grotesk" src="https://user-images.githubusercontent.com/13808824/91315628-348ee480-e7b8-11ea-9acb-b97bf4ada0ff.png">

**Comment by thlinard** [comment]
Example with Encode Sans VF 3.002 (Thin weight + `lnum` feature and Black weight + `onum` feature) https://github.com/google/fonts/tree/master/ofl/encodesans

<img width="1583" alt="Encode Sans" src="https://user-images.githubusercontent.com/13808824/91315900-833c7e80-e7b8-11ea-9c9a-cf197a10ddff.png">

**Comment by vv-monsalve** [comment]
PR 59 about math signs was merged, but it seems that Thin master alignment could be enhanced.

![Screen Shot 2020-11-10 at 16 39 05](https://user-images.githubusercontent.com/48698976/98745861-5bee5a00-2382-11eb-8902-f64d414b36a5.png)

**Comment by vv-monsalve** [comment]
Solved
