### ISSUE TITLE
Build TTF files and run Font Bakery automatically on Travis CI

### ISSUE THREAD

**Issue by felipesanches** [marcologous/hanken-grotesk#7]

**Comment by marcologous** [comment]
Hey @felipesanches ! I have merged some edits with the master repo. Will you be able to pull that to your clone/branch to run the autohinting? fontbakery flagged: 

> FAIL This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into an integer value.
> 
> This can be accomplished by using the 'gftools fix-hinting' command.

Thoughts?
